spring:
  liquibase:
    contexts: dev

  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

app:
  storage:
    location: uploads
  email:
    url: http://localhost:8080

