spring:
  datasource:
    url: jdbc:mysql://mysql:3306/movieclub
    username: root
    password: tajnehaslo
  liquibase:
    contexts: prod

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

app:
  storage:
    location: uploads


