spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml

  profiles:
    active: dev
server:
  servlet:
    session:
      cookie:
        max-age: 259200
      timeout: 43200